version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    command: uvicorn src.app.main:app --reload --host 0.0.0.0 --port 5000
    # environment:
    #   - DATABASE_URL=postgres://hello_fastapi:hello_fastapi@db:5432/hello_fastapi_dev
    # depends_on:
    #   - db

  frontend:
    build: ./services/frontend
    ports:
      - 8080:8080
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    # db:
    #   image: postgres:15.1
    #   expose:
    #     - 5432
    #   volumes:
    #     - postgres_data:/var/lib/postgresql/data/
    #   environment:
    #     - POSTGRES_USER=hello_fastapi
    #     - POSTGRES_PASSWORD=hello_fastapi
    #     - POSTGRES_DB=hello_fastapi_dev

    # volumes:
    #   postgres_data:
